# Generated by Django 4.1.13 on 2024-06-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
